server:
  log_level: debug

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: promtail-test

    static_configs:
      - targets: 
        - localhost
        labels:
          job: promtail-test
          __path__: /var/log/*.log

    pipeline_stages:
      - regex:
          expression: '^(?P<dateTimeOffset>\S+ \S+ \S+?) \[(?P<level>\w+)\] \[(?P<controller>\w+)\] \[(?P<ipAddress>\S+)\] (?P<message>[^{]+)(?P<context>.*)$'

      - labels:
          level:
          controller:
          ipAddress:
          message:
      
      - timestamp:
          source: dateTimeOffset
          format: '2006-01-02 15:04:05.999 -07:00'
